### DISCUSSION TITLE
Using a WAF from cloudflare

### DISCUSSION THREAD

**Discussion by gilesknap** [gilesknap/tpi-k3s-ansible#55] [Ideas]
I like to get all my certificates from lets_encrypt, including for services that I do not intend to expose on the internet. It turns out that if you have a Web Application Firewall, you can restrict traffic to your application subdomains to only allow letsencrypt challenges through, like so with Cloudflare's WAF:
![image](https://github.com/user-attachments/assets/2fa9ab7a-9647-44e4-a973-8fd4e1c154a9)
![image](https://github.com/user-attachments/assets/68623767-6ed7-488b-967d-9f73458cba86)

I have this working really well. However my approach is not yet that secure, because although all traffic directed at my DNS name will go through the WAF, my router WAN is still directly connected to the internet (and port forwarding HTTPS/HTTP to my cluster) i.e.
![image](https://github.com/user-attachments/assets/bf7a6364-ca34-4f14-bb95-f5bdb738b83c)

I originally planned to use firewalld to restrict source IPs to Cloudflare. But this is a fail as all incomming addresses look like they come from the router.

TODO: I believe that using a cloudflare tunnel can solve this as then all traffic would be forced to come through the tunnel and I need open no ports on my router. This appears to confirm that it can work https://community.cloudflare.com/t/waf-and-zero-trust-tunnel-at-the-same-time-does-that-work-for-a-website/601929

 @procinger I have not fully understood how you are using cloudflare tunnels - do you think the above is workable? thanks!

**Comment by gilesknap** [comment]
UPDATE: I just managed to make this work just using cloudflared in my ansible execution environment contianer as an experiment. I can confirm that the WAF rules were fully applied and that my Router was forwarding nothing.

The slight wrinkle is that as things stand I seem to need to set up a tunnel per application - which is a bit fiddly just to occasionally allow certificate requests through.
- I was able to ask for multiple subdomains to be added to a tunnel
  - cloudflared tunnel route dns test2 grafana.gkcluster.org
  - cloudflared tunnel route dns test2 echo.gkcluster.org 
- But when configuring the tunnel I needed to specify a specific endpoint URL (like below) which ended up using local DNS to route to the cluster with correct headers.
- What I really want is for the headers to be passed through to the origin - perhaps this is possible?

```yaml
url: https://grafana.gkcluster.org
tunnel: XXXXX
credentials-file: /root/.cloudflared/XXXX.json
```

**Comment by gilesknap** [comment]
I've tried running the tunnel direct from the control plane node using this config.yaml
```yaml
tunnel: 4e7be7c3-9471-49eb-8ea0-948c67cb008d
credentials-file: /home/ansible/.cloudflared/4e7be7c3-9471-49eb-8ea0-948c67cb008d.json

ingress:
  - hostname: "*.gkcluster.org"
    service: https://localhost
  - service: http_status:404
```

But I get this:
```
2025-02-22T13:54:07Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: tls: failed to verify certificate: x509: certificate is valid for ingress.local, not localhost" connIndex=3 event=1 ingressRule=0 originService=https://localhost:443
```

Which I take to mean the headers are not being forwarded to the origin.

**Comment by gilesknap** [comment]
So this works but seems like madness:
```yaml
tunnel: 4e7be7c3-9471-49eb-8ea0-948c67cb008d
credentials-file: /home/ansible/.cloudflared/4e7be7c3-9471-49eb-8ea0-948c67cb008d.json

ingress:
  - hostname: grafana.gkcluster.org
    service: https://grafana.gkcluster.org
  - hostname: echo.gkcluster.org
    service: https://echo.gkcluster.org
  - service: http_status:404
```

and `/etc/hosts` on the control plane node where cloudflared is running:
```
127.0.0.1       grafana.gkcluster.org
127.0.0.1       echo.gkcluster.org
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters
```

**Reply by gilesknap** [reply]
So what is happening here is that the host header of the service matches the host header of the incoming request (by explicitly listing each hostname) and routes to the local host because that host name is also in etc/hosts. (if you don't have that then you get an infinite reference loop back through cloudflare)

If the host header is just 'localhost' then K8S ingress is not interested and would not know which K8S service to route to. 

If the tunnel passed the host header on to the origin then all would be well. However perhaps I'm misusing the tunnel in expecting this. 

Another approach could be to use one host name and use paths for the various apps. However I did not want to do that as the ingress configuration gets more fiddly. Even so, would this be any better?

**Reply by gilesknap** [reply]
It looks like the below is the official way to do what I am trying to do [see docs](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/origin-configuration/#httphostheader). 

The difference to just saying `service: https://echo.gkcluster.org` is that the host name is not used for routing so I do not need to mess with the `etc/hosts` file (or use internal DNS routing - but I have that anyway for internal services)

So this is a solution but I don't like it.

```yaml
tunnel: 4e7be7c3-9471-49eb-8ea0-948c67cb008d
credentials-file: /home/ansible/.cloudflared/4e7be7c3-9471-49eb-8ea0-948c67cb008d.json

ingress:
  - hostname: echo.gkcluster.org
    service: https://localhost
    originRequest:
      httpHostHeader: echo.gkcluster.org
      originServerName: echo.gkcluster.org
  - hostname: grafana.gkcluster.org
    service: https://localhost
    originRequest:
      httpHostHeader: grafana.gkcluster.org
      originServerName: grafana.gkcluster.org
  - hostname: dashboard.gkcluster.org
    service: https://localhost
    originRequest:
      httpHostHeader: dashboard.gkcluster.org
      originServerName: dashboard.gkcluster.org
  - hostname: longhorn.gkcluster.org
    service: https://localhost
    originRequest:
      httpHostHeader: longhorn.gkcluster.org
      originServerName: longhorn.gkcluster.org
  - hostname: argocd.gkcluster.org
    service: https://localhost
    originRequest:
      httpHostHeader: argocd.gkcluster.org
      originServerName: argocd.gkcluster.org
  - hostname: "*"
    service: hello_world
```

I don't like it because I believe the tunnel client could support a much more straight forward config like:
```yaml
tunnel: 4e7be7c3-9471-49eb-8ea0-948c67cb008d
credentials-file: /home/ansible/.cloudflared/4e7be7c3-9471-49eb-8ea0-948c67cb008d.json

ingress:
  - hostname: "*.gkcluster.org"
    service: https://localhost
    originRequest:
      headersAndNameFromSource: true
  - service: http_status:404
```

Then we just rely on the ingresses and the WAF to control what traffic comes through and don't have to repeat all of the host names.

**Reply by procinger** [reply]
> It looks like the below is the official way to do what I am trying to do [see docs](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/origin-configuration/#httphostheader).
> 
> The difference to just saying `service: https://echo.gkcluster.org` is that the host name is not used for routing so I do not need to mess with the `etc/hosts` file (or use internal DNS routing - but I have that anyway for internal services)
> 
> So this is a solution but I don't like it.
> 
> ```yaml
> tunnel: 4e7be7c3-9471-49eb-8ea0-948c67cb008d
> credentials-file: /home/ansible/.cloudflared/4e7be7c3-9471-49eb-8ea0-948c67cb008d.json
> 
> ingress:
>   - hostname: echo.gkcluster.org
>     service: https://localhost
>     originRequest:
>       httpHostHeader: echo.gkcluster.org
>       originServerName: echo.gkcluster.org
>   - hostname: grafana.gkcluster.org
>     service: https://localhost
>     originRequest:
>       httpHostHeader: grafana.gkcluster.org
>       originServerName: grafana.gkcluster.org
>   - hostname: dashboard.gkcluster.org
>     service: https://localhost
>     originRequest:
>       httpHostHeader: dashboard.gkcluster.org
>       originServerName: dashboard.gkcluster.org
>   - hostname: longhorn.gkcluster.org
>     service: https://localhost
>     originRequest:
>       httpHostHeader: longhorn.gkcluster.org
>       originServerName: longhorn.gkcluster.org
>   - hostname: argocd.gkcluster.org
>     service: https://localhost
>     originRequest:
>       httpHostHeader: argocd.gkcluster.org
>       originServerName: argocd.gkcluster.org
>   - hostname: "*"
>     service: hello_world
> ```
> 
> I don't like it because I believe the tunnel client could support a much more straight forward config like:
> 
> ```yaml
> tunnel: 4e7be7c3-9471-49eb-8ea0-948c67cb008d
> credentials-file: /home/ansible/.cloudflared/4e7be7c3-9471-49eb-8ea0-948c67cb008d.json
> 
> ingress:
>   - hostname: "*.gkcluster.org"
>     service: https://localhost
>     originRequest:
>       headersAndNameFromSource: true
>   - service: http_status:404
> ```
> 
> Then we just rely on the ingresses and the WAF to control what traffic comes through and don't have to repeat all of the host names.

I have [deactivated](https://github.com/procinger/turing-pi-v2-cluster/blob/main/roles/k3s-server/tasks/main.yml#L22) traefik in my setup and roll out istio with istio-gateway.

I then [configure](https://github.com/procinger/turing-pi-v2-cluster/blob/main/kubernetes-services/additions/istio-gateway/non-tls-gateway.yaml) a simple gateway, `hosts: *`
This should of course never be done in prod environments!

In cloudflared [configuration](https://github.com/procinger/turing-pi-v2-cluster/blob/main/roles/cloudflare/tasks/main.yml#L33) I have configured two ingress (exmaple.net & *.example.net) to forward every incoming traffik to the istio gateway service.

A [VirtualService](https://istio.io/latest/docs/reference/config/networking/virtual-service/) is then used to specify which K8S service is to be resolved when a request arrives for a specific domain name
```
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: argo-cd-virtualservice
  namespace: argo-cd
spec:
  hosts:
    - "argocd.example.net"
  gateways:
    - istio-gateway/non-tls-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: argo-cd-argocd-server
            port:
              number: 80
```
I don't know at the moment whether this is a good solution. If anyone has found this via a search engine :tm: , please note that the setup I have described is far, far away from production ready :sweat_smile:
