### ISSUE TITLE
Add TLS to dashboard and grafana

### ISSUE THREAD

**Issue by gilesknap** [gilesknap/tpi-k3s-ansible#25]
I'd like to have certificates for my internal only ingresses but I don't know how to do that.

Let's Encrypt cert manager requires that the URL it signs is publicly contactable. But I do not wish to publish sensitive services like these on a public URL.

**Comment by gilesknap** [comment]
@cjreyn do you use let's encrypt for intranet certificates, or something else?

**Comment by gilesknap** [comment]
It looks like cloudflare certificate management as an alternative may solve this problem https://drunkcoding.net/posts/ks-04-cert-manager-alternative-with-cloudflare/

**Comment by cjreyn** [comment]
We use a wildcard for non subdomain sites, but for those with subdomains we use let's encrypt. We URL filter to allow only the let's encrypt challenge URL through the WAF.

**Comment by gilesknap** [comment]
@cjreyn thanks that sounds like what I want. But where do those URL filters go? It sounds like it would happen before the ingress?

**Comment by cjreyn** [comment]
Yeah a small proxy before the ingress. But you might also need a DNS solution worked out, depending on what your ISP offers. So maybe the Cloudflare route is better...

**Comment by gilesknap** [comment]
I've had a play with this and it looks like I can make it work by adding a new subdomain to noip for each ingress I want (I have 25 names for my subscription). I can make the same URL route internally using etc/hosts which is OK for my single workstation setup (but I might put up an internal DNS for that).
The details of how to do a filter could be extracted from here
https://community.fortinet.com/t5/FortiGate/Technical-Tip-How-to-allow-Let-s-Encrypt-traffic-through-the/ta-p/334464

But I have a little issue of where to put a filter. What I really want is for my router's firewall to handle this, but it is not up to the task.

**Comment by gilesknap** [comment]
It looks like I'll be going with cloudflare.

I have this working with echo service. 

The cert update and download is out of band but the certs can be long lived and not exposed to the internet as cloudflare will proxy the site.

**Comment by gilesknap** [comment]
Hmmm.

Cloudflare works great for external access via cloudflare DNS resolution and proxy. Cloudflare is terminating the SSL with its own generated Cert. It is then making another SSL hop to my ingress using my issued Origin Server Cert.

But when I route directly to my ingress from the local subnet, I see the Origin Server Cert directly and that does not have a certificate chain. 

This url was routed externally through DNS
![image](https://github.com/user-attachments/assets/ba6caee1-9822-475f-bb05-60388a556865)

This url was routed locally direct to the ingress
![image](https://github.com/user-attachments/assets/1a13917d-2726-44ac-b03d-d8dfb433395b)

So use of an Origin Server Certificate is leading me down the same path as Let's Encrypt which is I can only use certs for externally facing services.

**Comment by gilesknap** [comment]
Cloudflare has given me a WAF (for free!)
![image](https://github.com/user-attachments/assets/8a880f4d-9d0d-481e-915f-7d5fd21b4452)

**Comment by gilesknap** [comment]
Now we can try to use @cjreyn's approach of filtering in let's encrypt certificate challenges.

**Comment by gilesknap** [comment]
Maybe I spent too much time on this but it's working!

I now have a domain name from cloudflare and have set up their WAF and a *.gkcluster.org DNS record.
I'm using cloudflare origin certificate for internet facing subdomains and let's encrypt for internal subdomains. The internal subdomains are currently addressable using entries in etc/hosts.

WAF rules are:
- allow letsencrypt through on HTTP for http://*/.well-known/acme-challenge/*
- allow 'echo.gkcluster.org' with managed challenge (captcha)
- block everything else

@cjreyn thanks for the tip!

Nobody gets to see my IP address because its proxied by cloudflare. But I assume it is possible to attack my IP address directly. 

I think I can configure my router to limit to IP addresses from cloudflare - next line of investigation.

**Comment by gilesknap** [comment]
Oh dear. I'm seeing the benfits of a WAF here:
![image](https://github.com/user-attachments/assets/b6e3fa7b-8fc5-4609-9ede-792fa2894273)

I appear to be under constant attack on my tiny little echo service:
![image](https://github.com/user-attachments/assets/3858010b-2679-4465-8090-48d0d166331d)

**Comment by gilesknap** [comment]
I've added firewalld with following rules to my control plane which has 80/433 forwarded but tests seem to show that this has not worked and I can still contact 80/433 from non-whitelisted IPS.

```yaml
- name: Open all ports on the local network
  ansible.posix.firewalld:
    source: 192.168.1.0/24
    interface: eth0
    state: enabled
    zone: trusted
    permanent: true
    immediate: true
  become: true

- name: Restrict external IP sources to Cloudflare for port 443 and 80
  ansible.posix.firewalld:
    rich_rule: >
      rule family="ipv4"
      source address="{{ item.1 }}"
      port protocol="tcp" port="{{ item.0 }}" accept
    permanent: true
    zone: public
    state: enabled
    immediate: true
  become: true
  vars:
    ports:
      - 80
      - 443
    cloudflare_ips:
      - 173.245.48.0/20
      - 103.21.244.0/22
      - 103.22.200.0/22
      - 103.31.4.0/22
      - 141.101.64.0/18
      - 108.162.192.0/18
      - 190.93.240.0/20
      - 188.114.96.0/20
      - 197.234.240.0/22
      - 198.41.128.0/17
      - 162.158.0.0/15
      - 104.16.0.0/13
      - 104.24.0.0/14
      - 172.64.0.0/13
      - 131.0.72.0/22
  loop: "{{ ports | product(cloudflare_ips) | list }}"
```
